"""Deterministic runnable-project outputs for the governed network-free demo."""

from __future__ import annotations

from pathlib import Path

from agentic_sdlc.task_execution_contracts import (
    ArtifactMaterializationProposal,
    ArtifactOutput,
    EngineeringArtifactType,
    TaskExecutionResult,
)
from agentic_sdlc.workspace_integration_contracts import (
    WorkspaceBoundTaskExecutionRequest,
)


API_DESIGN = """# URL Shortener API Design

## Shorten a URL

`POST /shorten` accepts JSON containing a valid absolute `http://` or `https://`
URL. A successful request returns `201 Created` with a unique short code and a
short URL. Repeating the same URL may return its existing code.

Malformed JSON, missing URLs, relative URLs, and unsupported schemes return
`400 Bad Request` with a stable JSON error category.

## Resolve a short code

`GET /{code}` redirects a known code to its original URL with `302 Found`. An
unknown code returns `404 Not Found` with a stable JSON error category.

URL expiration remains unresolved by the approved specification and is not part
of this prototype contract.
"""


STORAGE_DESIGN = """# URL Shortener Storage Design

The runnable demonstration uses a process-local in-memory repository because the
approved specification does not select a persistent storage technology.

The repository retains both `code -> original URL` and `original URL -> code`
mappings. The reverse mapping makes repeated shortening idempotent. Codes are
derived from a deterministic SHA-256 digest and a collision nonce; a candidate is
accepted only when it is unused or already belongs to the same URL.

This choice is intentionally nonpersistent: restarting the process loses every
mapping. A production design would replace the repository behind the domain
service while retaining uniqueness and lookup behavior.
"""


PYPROJECT = """[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "governed-url-shortener-demo"
version = "0.1.0"
description = "Dependency-free URL shortener generated by a governed SDLC demo"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
"""


PACKAGE_INIT = '''"""Runnable URL-shortener domain and WSGI application."""

from url_shortener.service import (
    InvalidURLError,
    UnknownShortCodeError,
    URLShortener,
)

__all__ = ["InvalidURLError", "UnknownShortCodeError", "URLShortener"]
'''


SERVICE = '''"""In-memory URL-shortening domain service."""

from __future__ import annotations

import base64
import hashlib
from threading import Lock
from urllib.parse import urlsplit


class URLShortenerError(Exception):
    """Base class for domain-level URL-shortener failures."""


class InvalidURLError(URLShortenerError):
    """Raised when a submitted URL is not an absolute HTTP(S) URL."""


class UnknownShortCodeError(URLShortenerError):
    """Raised when no original URL exists for a short code."""


class URLShortener:
    """Deterministic, collision-safe, process-local URL repository."""

    def __init__(self) -> None:
        self._url_by_code: dict[str, str] = {}
        self._code_by_url: dict[str, str] = {}
        self._lock = Lock()

    def shorten(self, url: str) -> str:
        """Return a stable unique code for one valid absolute HTTP(S) URL."""

        validated = _validate_url(url)
        with self._lock:
            existing = self._code_by_url.get(validated)
            if existing is not None:
                return existing

            nonce = 0
            while True:
                code = _candidate_code(validated, nonce)
                owner = self._url_by_code.get(code)
                if owner is None or owner == validated:
                    self._url_by_code[code] = validated
                    self._code_by_url[validated] = code
                    return code
                nonce += 1

    def resolve(self, code: str) -> str:
        """Return the original URL for a known code."""

        if not isinstance(code, str) or not code:
            raise UnknownShortCodeError("Unknown short code.")
        with self._lock:
            try:
                return self._url_by_code[code]
            except KeyError as error:
                raise UnknownShortCodeError(
                    f"Unknown short code: {code}."
                ) from error


def _validate_url(url: str) -> str:
    if not isinstance(url, str) or not url or url != url.strip():
        raise InvalidURLError("URL must be a non-empty absolute HTTP(S) URL.")
    if any(character.isspace() for character in url):
        raise InvalidURLError("URL must not contain whitespace.")
    try:
        parsed = urlsplit(url)
        port = parsed.port
    except ValueError as error:
        raise InvalidURLError("URL authority is malformed.") from error
    if (
        parsed.scheme.lower() not in {"http", "https"}
        or not parsed.netloc
        or parsed.hostname is None
        or (port is not None and not 1 <= port <= 65535)
    ):
        raise InvalidURLError("URL must be an absolute HTTP(S) URL.")
    return url


def _candidate_code(url: str, nonce: int) -> str:
    digest = hashlib.sha256(f"{url}\\0{nonce}".encode("utf-8")).digest()
    return base64.urlsafe_b64encode(digest[:6]).decode("ascii").rstrip("=")
'''


APP = '''"""Thin dependency-free WSGI adapter for the URL-shortener service."""

from __future__ import annotations

import json
import os
from collections.abc import Callable, Iterable
from typing import Any
from urllib.parse import unquote
from wsgiref.simple_server import make_server

from url_shortener.service import InvalidURLError, UnknownShortCodeError, URLShortener

StartResponse = Callable[[str, list[tuple[str, str]]], Any]


class URLShortenerApplication:
    """WSGI application exposing shorten and resolve operations."""

    def __init__(
        self,
        service: URLShortener | None = None,
        *,
        base_url: str = "http://127.0.0.1:8000",
    ) -> None:
        self.service = service or URLShortener()
        self.base_url = base_url.rstrip("/")

    def __call__(
        self, environ: dict[str, Any], start_response: StartResponse
    ) -> Iterable[bytes]:
        method = str(environ.get("REQUEST_METHOD", "GET")).upper()
        path = str(environ.get("PATH_INFO", "/"))
        if path == "/shorten":
            if method == "POST":
                return self._shorten(environ, start_response)
            return _json_response(
                start_response,
                "405 Method Not Allowed",
                {"error": "method_not_allowed"},
            )
        if method == "GET" and path.startswith("/") and path != "/":
            return self._resolve(unquote(path[1:]), start_response)
        return _json_response(
            start_response, "404 Not Found", {"error": "not_found"}
        )

    def _shorten(
        self, environ: dict[str, Any], start_response: StartResponse
    ) -> Iterable[bytes]:
        try:
            length = int(environ.get("CONTENT_LENGTH") or "0")
            if length < 1 or length > 1_000_000:
                raise ValueError
            stream = environ["wsgi.input"]
            payload = json.loads(stream.read(length).decode("utf-8"))
            if not isinstance(payload, dict) or not isinstance(payload.get("url"), str):
                raise ValueError
        except (KeyError, TypeError, ValueError, UnicodeDecodeError, json.JSONDecodeError):
            return _json_response(
                start_response,
                "400 Bad Request",
                {"error": "invalid_request", "message": "Expected JSON with a URL."},
            )
        try:
            code = self.service.shorten(payload["url"])
        except InvalidURLError as error:
            return _json_response(
                start_response,
                "400 Bad Request",
                {"error": "invalid_url", "message": str(error)},
            )
        return _json_response(
            start_response,
            "201 Created",
            {"code": code, "short_url": f"{self.base_url}/{code}"},
        )

    def _resolve(self, code: str, start_response: StartResponse) -> Iterable[bytes]:
        try:
            original_url = self.service.resolve(code)
        except UnknownShortCodeError:
            return _json_response(
                start_response,
                "404 Not Found",
                {"error": "unknown_code", "code": code},
            )
        start_response(
            "302 Found",
            [("Location", original_url), ("Content-Length", "0")],
        )
        return [b""]


def _json_response(
    start_response: StartResponse, status: str, payload: dict[str, object]
) -> list[bytes]:
    body = json.dumps(payload, sort_keys=True).encode("utf-8")
    start_response(
        status,
        [
            ("Content-Type", "application/json; charset=utf-8"),
            ("Content-Length", str(len(body))),
        ],
    )
    return [body]


def main() -> None:
    host = os.environ.get("URL_SHORTENER_HOST", "127.0.0.1")
    port = int(os.environ.get("URL_SHORTENER_PORT", "8000"))
    application = URLShortenerApplication(base_url=f"http://{host}:{port}")
    with make_server(host, port, application) as server:
        print(f"URL shortener listening on http://{host}:{port}")
        server.serve_forever()


if __name__ == "__main__":
    main()
'''


TESTS = '''"""Executable tests for the generated URL-shortener project."""

from __future__ import annotations

import json
import unittest
from io import BytesIO
from typing import Any

from url_shortener.app import URLShortenerApplication
from url_shortener.service import InvalidURLError, UnknownShortCodeError, URLShortener


def invoke_wsgi(
    application: URLShortenerApplication,
    method: str,
    path: str,
    payload: dict[str, object] | None = None,
) -> tuple[str, dict[str, str], bytes]:
    body = b"" if payload is None else json.dumps(payload).encode("utf-8")
    environ: dict[str, Any] = {
        "REQUEST_METHOD": method,
        "PATH_INFO": path,
        "CONTENT_LENGTH": str(len(body)),
        "wsgi.input": BytesIO(body),
    }
    captured: dict[str, object] = {}

    def start_response(status: str, headers: list[tuple[str, str]]) -> None:
        captured["status"] = status
        captured["headers"] = dict(headers)

    response = b"".join(application(environ, start_response))
    return (
        str(captured["status"]),
        dict(captured["headers"]),  # type: ignore[arg-type]
        response,
    )


class URLShortenerServiceTests(unittest.TestCase):
    def setUp(self) -> None:
        self.service = URLShortener()

    def test_shortening_valid_url_returns_code(self) -> None:
        code = self.service.shorten("https://example.com/path")
        self.assertRegex(code, r"^[A-Za-z0-9_-]{8}$")

    def test_different_urls_receive_distinct_codes(self) -> None:
        first = self.service.shorten("https://example.com/first")
        second = self.service.shorten("https://example.com/second")
        self.assertNotEqual(first, second)

    def test_repeated_shortening_is_idempotent(self) -> None:
        url = "https://example.com/repeated"
        self.assertEqual(self.service.shorten(url), self.service.shorten(url))

    def test_known_code_resolves_to_original_url(self) -> None:
        url = "https://example.com/original"
        self.assertEqual(self.service.resolve(self.service.shorten(url)), url)

    def test_unknown_code_raises_domain_error(self) -> None:
        with self.assertRaises(UnknownShortCodeError):
            self.service.resolve("missing")

    def test_invalid_urls_are_rejected(self) -> None:
        for url in ("", "example.com", "/relative", "ftp://example.com", "https://bad host"):
            with self.subTest(url=url), self.assertRaises(InvalidURLError):
                self.service.shorten(url)


class URLShortenerHTTPTests(unittest.TestCase):
    def setUp(self) -> None:
        self.application = URLShortenerApplication(
            URLShortener(), base_url="http://short.test"
        )

    def test_post_shorten_returns_created_response(self) -> None:
        status, _, body = invoke_wsgi(
            self.application,
            "POST",
            "/shorten",
            {"url": "https://example.com/http"},
        )
        payload = json.loads(body)
        self.assertEqual(status, "201 Created")
        self.assertEqual(payload["short_url"], f"http://short.test/{payload['code']}")

    def test_post_shorten_rejects_invalid_url(self) -> None:
        status, _, body = invoke_wsgi(
            self.application,
            "POST",
            "/shorten",
            {"url": "ftp://example.com/not-supported"},
        )
        self.assertEqual(status, "400 Bad Request")
        self.assertEqual(json.loads(body)["error"], "invalid_url")

    def test_get_shorten_rejects_wrong_method(self) -> None:
        status, _, body = invoke_wsgi(self.application, "GET", "/shorten")
        self.assertEqual(status, "405 Method Not Allowed")
        self.assertEqual(json.loads(body)["error"], "method_not_allowed")

    def test_get_known_code_redirects(self) -> None:
        url = "https://example.com/redirect"
        code = self.application.service.shorten(url)
        status, headers, body = invoke_wsgi(self.application, "GET", f"/{code}")
        self.assertEqual(status, "302 Found")
        self.assertEqual(headers["Location"], url)
        self.assertEqual(body, b"")

    def test_get_unknown_code_returns_not_found(self) -> None:
        status, _, body = invoke_wsgi(self.application, "GET", "/unknown")
        self.assertEqual(status, "404 Not Found")
        self.assertEqual(json.loads(body)["error"], "unknown_code")


if __name__ == "__main__":
    unittest.main()
'''


GENERATED_README = """# Governed URL Shortener Demo

This dependency-free Python URL shortener is engineering output generated by the
governed Agentic SDLC demonstration. The approved workflow produced semantic
artifacts, validated file-materialization intents, derived change sets, and
transactionally created this project inside a disposable isolated workspace.

## Architecture

`URLShortener` contains the domain rules and process-local in-memory mappings.
`URLShortenerApplication` is a thin WSGI adapter. The service accepts absolute
HTTP(S) URLs, generates stable collision-checked short codes, resolves known
codes, and reports typed errors for invalid URLs and unknown codes.

Storage is deliberately in-memory and is lost when the process exits. URL
expiration remains unresolved by the approved specification and is not
implemented.

## Run

Python 3.11 or newer is required. No third-party runtime dependency is needed.

```bash
PYTHONPATH=src python -m url_shortener.app
```

The server binds to `127.0.0.1:8000` by default. Override it with
`URL_SHORTENER_HOST` and `URL_SHORTENER_PORT`.

## Test

```bash
PYTHONPATH=src python -m unittest discover -s tests -v
```

Tests run entirely in-process and require no network access.

## HTTP API

Shorten a URL:

```bash
curl -i -X POST http://127.0.0.1:8000/shorten \\
  -H 'Content-Type: application/json' \\
  -d '{"url":"https://example.com/path"}'
```

The `201 Created` JSON response contains `code` and `short_url`. Resolve the code:

```bash
curl -i http://127.0.0.1:8000/<code>
```

A known code returns `302 Found`; an unknown code returns `404 Not Found`.

## Assumptions and trade-offs

- Repeated shortening of the same URL returns the existing code.
- SHA-256-derived candidates plus collision checking provide deterministic codes.
- Persistence, expiration, analytics, authentication, and repository promotion
  remain outside this prototype.
- The orchestrator does not execute this generated source or its tests. Execution
  commands above are manual reviewer/development actions against the exported copy.
"""


DETERMINISTIC_PROJECT_FILES = (
    ("README.md", GENERATED_README),
    ("pyproject.toml", PYPROJECT),
    ("src/url_shortener/__init__.py", PACKAGE_INIT),
    ("src/url_shortener/app.py", APP),
    ("src/url_shortener/service.py", SERVICE),
    ("tests/test_service.py", TESTS),
)


def write_deterministic_project(
    root: Path,
    files: tuple[tuple[str, str], ...] = DETERMINISTIC_PROJECT_FILES,
) -> Path:
    """Write one isolated deterministic project fixture for regression tests."""

    for relative_path, contents in files:
        destination = root / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(contents, encoding="utf-8")
    return root


def deterministic_demo_result(
    request: WorkspaceBoundTaskExecutionRequest,
) -> TaskExecutionResult:
    """Return realistic semantic outputs without filesystem or tool authority."""

    outputs_by_source_key: dict[str, tuple[ArtifactOutput, ...]] = {
        "define_api": (
            ArtifactOutput(
                artifact_type=EngineeringArtifactType.DESIGN,
                logical_name="url-shortener-api-design",
                content=API_DESIGN,
            ),
        ),
        "define_storage": (
            ArtifactOutput(
                artifact_type=EngineeringArtifactType.DESIGN,
                logical_name="url-shortener-storage-design",
                content=STORAGE_DESIGN,
            ),
        ),
        "build_service": (
            ArtifactOutput(
                artifact_type=EngineeringArtifactType.OTHER,
                logical_name="generated-project-metadata",
                content=PYPROJECT,
            ),
            ArtifactOutput(
                artifact_type=EngineeringArtifactType.SOURCE,
                logical_name="url-shortener-package",
                content=PACKAGE_INIT,
            ),
            ArtifactOutput(
                artifact_type=EngineeringArtifactType.SOURCE,
                logical_name="url-shortener-domain-service",
                content=SERVICE,
            ),
            ArtifactOutput(
                artifact_type=EngineeringArtifactType.SOURCE,
                logical_name="url-shortener-wsgi-application",
                content=APP,
            ),
        ),
        "verify_service": (
            ArtifactOutput(
                artifact_type=EngineeringArtifactType.TEST,
                logical_name="url-shortener-executable-tests",
                content=TESTS,
            ),
        ),
        "document_service": (
            ArtifactOutput(
                artifact_type=EngineeringArtifactType.DOCUMENTATION,
                logical_name="generated-project-readme",
                content=GENERATED_README,
            ),
        ),
    }
    targets_by_source_key: dict[str, tuple[str, ...]] = {
        "build_service": (
            "pyproject.toml",
            "src/url_shortener/__init__.py",
            "src/url_shortener/service.py",
            "src/url_shortener/app.py",
        ),
        "verify_service": ("tests/test_service.py",),
        "document_service": ("README.md",),
    }
    outputs = outputs_by_source_key[request.task.source_key]
    targets = targets_by_source_key.get(request.task.source_key, ())
    return TaskExecutionResult(
        request_id=request.request_id,
        attempt_id=request.attempt_id,
        task_id=request.task_id,
        summary=f"Produced governed runnable output for {request.task_id}.",
        outputs=outputs,
        materialization_proposals=tuple(
            ArtifactMaterializationProposal(output_index=index, target_path=path)
            for index, path in enumerate(targets, start=1)
        ),
        assumptions=(
            "The runnable prototype uses process-local in-memory storage.",
        ),
        risks=(
            "Process restart loses shortened URL mappings.",
        ),
    )
